spring:
  datasource:
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER_NAME}    
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080